[package]
name = "embed-serial-protocol"
version = "0.2.1"
edition = "2024"

[dependencies]
bilge = "0.2.0"
crc = "3.3.0"
embedded-hal-nb = "1.0.0"
embedded-io = "0.6.1"
heapless = "0.9.1"
log = "0.4.21"
nb = "1.1.0"
slippers = "0.1.4"
